[project]
name = 'Artisanal-Mass-Production-Boutique-Factory'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.industrial-intimacy-scaling-protocol]
path = 'contracts/industrial-intimacy-scaling-protocol.clar'
clarity_version = 3
epoch = 'latest'

[contracts.machine-learning-grandmother-recipe-simulator]
path = 'contracts/machine-learning-grandmother-recipe-simulator.clar'
clarity_version = 3
epoch = '3.2'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
